name: moountain
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Moountain
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#feaa75'
    - '#9d6236'
    - '#148bb7'
    - '#fefe6a'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
